units:
  # Proxy Spacing Variables
  kx: U
  ky: U
  # Padding Variables
  px: kx + 2
  py: ky + 2
points:
  zones:
    main:
      anchor:
        shift: [ 150, -150 ]
      key:
        padding: 1ky
        spread: 1kx
      columns:
        pinky:
          key.stagger: 0
          key.column_net: P14
        ring:
          key.stagger: 0
          key.column_net: P16
        middle:
          key.stagger: 8
          key.column_net: P10
        index:
          key.stagger: 8
          key.column_net: P07
        inner:
          key.stagger: -8
          key.column_net: P08
        aditional:
          key.stagger: -8
          key.column_net: P09
      rows:
        bottom:
          row_net: P18
        home:
          row_net: P19
        num:
          row_net: P20
        top:
          row_net: P21
    thumb:
      key:
        padding: 1ky
        spread: 1kx
      anchor:
        ref: main_aditional_bottom
        shift: [ 0,-25 ]
        rotate: -45
      rows:
        main:
          row_net: P15
      columns:
        one:
          key.column_net: P08
        two:
          key.stagger: -kx/2
          key.column_net: P09
outlines:
  _main_board:
    - what: rectangle
      where: -main_aditional_bottom
      size: [ px, py ]
      bound: true
      expand: 2
      fillet: 1
  _thumb_connector:
    - what: rectangle
      where: main_aditional_bottom
      size: [ px, 50 ]
      bound: true
      expand: 2
      fillet: 1
  _microcontroller:
    - what: rectangle
      where: main_aditional_top
      size: [ px*3, 40 ]
      fillet: 1
  _reset:
    - what: rectangle
      where: main_aditional_num
      size: [ px*3, 20 ]
      fillet: 1
  board:
    - _main_board
    - _thumb_connector
    - _microcontroller
    - _reset
pcbs:
  main_pcb:
    outlines:
      main:
        outline: board
    footprints:
      mx_hotswap:
        what: mx
        where: true
        params:
          keycaps: false
          reverse: true
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [ 0, -5 ]
      promicro:
        what: promicro
        params:
          orientation: "down"
        where:
          ref: main_aditional_top
          shift: [ px, 2 ]
          rotate: -90
      reset:
        what: button
        params:
          from: GND
          to: RST
        where:
          ref: main_aditional_num
          shift: [ 14, -2 ]
          rotate: 90
      trrs:
        what: trrs
        where:
          ref: main_aditional_num
          shift: [ 31.5, -4 ]
          rotate: 270
        params:
          reverse: true
          symmetric: true
          A: VCC
          B: VCC
          C: GND
          D: P0
      holeTopLeft:
        what: mountinghole
        where:
          ref: main_pinky_num
          shift: [ 0.5kx, -0.5ky ]
      holeTopRight:
        what: mountinghole
        where:
          ref: main_aditional_top
          shift: [ 0, 0.67ky ]
      holeBottom:
        what: mountinghole
        where:
          ref: main_aditional_bottom
          shift: [ 0kx, -0.57ky ]
cases:
  bottom:
    - name: board
      extrude: 1